kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: app2
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          system-reserved: memory=4Gi
    extraPortMappings:
    - containerPort: 30002
      hostPort: 30002
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp